<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle('Stellenanzeigen texten')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/index.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/CreateNewButtons.js')
            ->prependFile($this->basePath() . '/js/added_functions.js')
            ->prependFile($this->basePath() . '/tinymce_4.0.11/tinymce/js/tinymce/tinymce.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class='main-content'>
            <div class='login_form'>
                <?php
                $form = $this->form;
                $form->setAttribute('action', $this->url('auth/default', array('controller' => 'index', 'action' => 'login')));
                $form->prepare();
                
                echo $this->form()->openTag($form);
                ?>
                
                <div class='registration_formular'>
                
                <div><?php echo $this->messages?></div>
                    <div class='div_row'>
                        <div class='reg_label'>Benutzername</div>
                        <div class='reg_textfield'><?php    echo $this->formRow($form->get('user_email')); ?></div>
                    </div>
                    <div class='div_row'>
                        <div class='reg_label'>Passwort</div>
                        <div class='reg_textfield'><?php    echo $this->formRow($form->get('user_passwort')); ?></div>
                    </div>
                    
                
                       
                    <div class='submit'><?php    echo $this->formSubmit($form->get('submit')); ?></div>
                    <div class='password_forget'>
                        <a href="<?php echo $this->url('auth/default', array('controller' => 'registration', 'action' => 'forgotten-password'));?>"><?php echo $this->translate('Passwort vergessen'); ?></a>
                    </div>
                    <?php
                    echo $this->form()->closeTag();
                    ?>
                    
                </div>
            </div>
        </div>
    </body>
</html>