<?php include_once('public/includes/admin/header.php'); ?>

<div class="acp">
<div class="middle">
    <div class="uk-container uk-container-center">
        <div class="uk-grid uk-grid-divider">
            <div class="uk-width-1-4">
                <?php include_once('public/includes/admin/sidebar.php'); ?>
            </div>

            <div class="uk-width-3-4">
                <div class="uk-grid" data-uk-grid-match>
                    <div class="uk-width-3-4"><h1><i class="uk-icon-font"></i> Text-Optimierer</h1></div>
                    <div class="uk-width-1-4">
                        <a href="#" id="markierungenAufheben" class="uk-button uk-width-1-1 markierungenAufheben"><i class="uk-icon-times"></i> Marker löschen</a>
                    </div>
                </div>
                <div class="uk-grid pruef-buttons">
                    <div id="buttonset_1" class="uk-width-1-4">
                        <a href="#" data-action="checkFloskel" id="floskeln" class="editorButton uk-button uk-width-1-1 floskeln"><i class="uk-icon"></i> Floskeln</a>
                        <a href="#" data-action="checkNegativeWoerter" id="negative_woerter" class="editorButton uk-button uk-width-1-1 negative-woerter"><i class="uk-icon"></i> Negative Wörter</a>
                        <a href="#" data-action="checkTextverstaendnis" id="textverstaendnis" class="editorButton uk-button uk-width-1-1 textverstaendnis"><i class="uk-icon"></i> Textverständnis</a>
                        <a href="#" data-action="checkAnglizismen" id="anglizismen" class="editorButton uk-button uk-width-1-1 anglizismen"><i class="uk-icon"></i> Anglizismen</a>
                    </div>
                    <div id="buttonset_2" class="uk-width-1-4">
                        <a href="#" data-action="checkNominalstil" id="nominalstil" class="editorButton uk-button uk-width-1-1 nominalstil"><i class="uk-icon"></i> Nominalstil</a>
                        <a href="#" data-action="checkAktivPassiv" id="aktiv_passiv" class="editorButton uk-button uk-width-1-1 aktiv-passiv"><i class="uk-icon"></i> Aktiv-Passiv</a>
                    </div>
                    <div id="buttonset_3" class="uk-width-1-4">
                        <a href="#" data-action="checkWiederholung" id="wiederholungen" class="editorButton uk-button uk-width-1-1 wiederholungen"><i class="uk-icon"></i> Wiederholungen</a>
                    </div>
                    <div id="buttonset_4" class="uk-width-1-4">
                        <a href="#" data-action="checkWortlaenge" id="wortlaenge" class="editorButton uk-button uk-width-1-1 wortlaenge"><i class="uk-icon"></i> Wortlänge</a>
                        <a href="#" data-action="checkSatzlaenge" id="lange_saetze" class="editorButton uk-button uk-width-1-1 lange-saetze"><i class="uk-icon"></i> Lange Sätze</a>
                        <a href="#funktionen" class="uk-button uk-button-info uk-button-small uk-width-1-1" style="margin-top: 36px;"><i class="uk-icon-info-circle"></i> Erläuterungen</a>
                    </div>
                </div>
                </br>
                <!--
                <a class="uk-button editorDebugButton debugButton" style="width: 190px; display: none;"><i class="uk-icon-bug"></i> Debug <i style="font-size: 9px;">(wird bald entfernt)</i></a>
                <a class="uk-button editorDebugButton oldModeButton" style="width: 190px;"><i class="uk-icon-bug"></i> Alte Überprüfung</a>
                -->
                <div class='page_content'>
                    <div id='textarea_1' class="editor_container">
                        <textarea class="textarea_1" name="content" cols="50" rows="15">
                        </textarea>
                    </div>
                </div>

                <?php if (isset($arrStandardText)): ?>
                    <div class="uk-button-dropdown standardtextDropDown" data-uk-dropdown="{mode:'click'}">
                        <button class="uk-button uk-width-1-1 editorDebugButton standardtext">Standardtext
                            <i class="uk-icon-caret-down"></i></button>
                        <div class="uk-dropdown">
                            <ul class="uk-nav uk-nav-dropdown standardtextNav">

                                <?php foreach ($arrStandardText as $arrText): ?>
                                    <li>
                                        <a class="standardtextButton" data-id="<?= $arrText['id']; ?>" href="#"><?= $arrText['name']; ?></a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    </div>
                <?php endif; ?>
                <br>
                <?php if (isset($arrReports)): ?>
                    <div class="savedReports" style="display: <?php echo (count($arrReports) > 0 ? 'block' : 'none'); ?>;">
                        <h3 class="tm-article-subtitle">Gespeicherte Berichte</h3>
                        <ul class="reportList uk-list uk-list-striped uk-width-medium-1-1">
                            <?php foreach ($arrReports as $arrReport): ?>
                                <li data-id="<?= $arrReport['id']; ?>">
                                    <?= utf8_encode($arrReport['title']).' / '.utf8_encode($arrReport['company']); ?>
                                    <div style="float: right">
                                        <a class="reportLoad uk-icon-hover uk-icon-share" title="Lade <?= $arrReport['title'].' / '.$arrReport['company']; ?>" data-id="<?= $arrReport['id']; ?>" href="#"></a>
                                        <a class="reportTrash uk-icon-hover uk-icon-trash-o" title="Lösche <?= $arrReport['title'].' / '.$arrReport['company']; ?>" data-id="<?= $arrReport['id']; ?>" href="#"></a>
                                    </div>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                <?php endif; ?>

                <h2 id="funktionen">Die Funktionen im Überblick</h2>

                <p>Der Pulitzer-Preis ist bei Journalisten und Autoren ebenso begehrt,
                    wie der Oscar in der Filmindustrie. Der Stifter und Namensgeber des
                    Preises war der Journalist, Zeitungsverleger und Herausgeber Joseph
                    Pulitzer. Er bringt für uns die Regeln für gute Texte auf den Punkt:

                <p><strong>Schreibe kurz und sie werden es lesen,<br/>
                        schreibe klar und sie werden es verstehen,<br/>
                        schreibe anschaulich und sie werden es behalten.</strong></p>

                Die nachfolgenden Themenfelder helfen Ihnen, den Rat von Joseph Pulitzer
                umzusetzen.</p><br><br>

                <div class="uk-accordion" data-uk-accordion>

                    <h3 class="uk-accordion-title" style="background: #9ce3ff; border: 1px solid #444;">Floskeln<i class="accordion-arrow uk-icon-chevron-down"></i>
                    </h3>

                    <div class="uk-accordion-content">Floskeln sind Worthülsen, Blabla, Gefasel, Geschwafel, Binsenweisheiten, Selbstverständlichkeiten, Umschweife, Gemeinplätze, Banalitäten und somit nur überflüssiges Geschwätz. Verzichten Sie auf langweilige, kraftlose, inhaltsleere und nichtssagende Wörter! Alle Wörter, die wir in Ihrem Text als Floskeln einstufen, werden über den Button „Floskeln“ farblich markiert. Falls Sie das Ergebnis erschreckt, sollten Sie sich unter dem Menüpunkt „Checklisten, Infos“ die Informationen zu floskelfreien Stellenanzeigen ansehen. Dort erfahren Sie, was Bewerber unter den Begriffen „flexibel“ und „belastbar“ verstehen könnten. Die Bandbreite möglicher Interpretationen überrascht. Dieses Erlebnis kann helfen, konkreter zu formulieren. Sie entscheiden, ob Sie die markierten Floskel belassen, ersatzlos streichen oder ersetzen.</div>

                    <h3 class="uk-accordion-title" style="background: #c7d66f; border: 1px solid #444;">Negative Wörter<i class="accordion-arrow uk-icon-chevron-down"></i>
                    </h3>

                    <div class="uk-accordion-content">Beschreiben Sie Sachverhalte positiv. Sorgen Sie für gute Gefühle bei den Lesern. Verneinungen (nicht, keine, ohne, un...) und Wörter mit negativen Assoziationen führen zu Missklängen. Wir können nicht an etwas nicht denken. Sie kennen vermutlich das Beispiel mit dem rosa Elefanten. Nach der Aufforderung, nicht an einen rosa Elefanten zu denken, sieht praktisch jeder einen rosa Elefanten vor seinem geistigen Auge.
                        <br/><br/>
                        Klicken Sie auf „Negative Wörter“ und formulieren Sie die markierten Wörter positiv.
                    </div>

                    <h3 class="uk-accordion-title" style="background: #ffb979; border: 1px solid #444;">Textverständnis<i class="accordion-arrow uk-icon-chevron-down"></i>
                    </h3>

                    <div class="uk-accordion-content">Ob Leser einen Text verstehen, hängt vom Text, der Bildung des Lesers und weiteren Faktoren abhängig. Vergessen Sie nicht, dass Stellenausschreibungen Werbetexte sind. Wer liest schon Werbetexte mit voller Konzentration? Verwenden Sie daher einfache Worte. Vermeiden Sie Abkürzungen, Fachbegriffe und Fremdwörter wo immer es geht. Als Regel gilt die Empfehlung von Arthur Schopenhauer: „Man gebrauche gewöhnliche Worte und sage ungewöhnliche Dinge.“
                        <br/><br/>
                        Als Basis für die Überprüfung des Textverständnisses sind in Datenbank der TOOLBOX fast eine Million deutsche Wörter gespeichert. Jedes Wort, das nicht in diesem Grundwortschatz enthalten ist, wird markiert. Prüfen Sie kritisch, ob es ein bedeutungsgleiches oder ähnliches Wort gibt, das leichter verstanden wird.
                    </div>

                    <h3 class="uk-accordion-title" style="background: #ff8c87; border: 1px solid #444;">Anglizismen<i class="accordion-arrow uk-icon-chevron-down"></i>
                    </h3>

                    <div class="uk-accordion-content">Es gibt verschiedene Formen von Anglizismen. Anglizismen, die einem Lehnwortstatus gleich kommen, jedoch nicht phonetisch und grammatisch der deutschen Sprache angepasst sind (z.B. Sport, fair); Anglizismen, die neue Sachverhalte bezeichnen, für die keine deutsche Entsprechung existiert (z.B. E-Mail, Airbag) und Anglizismen die neben existierenden, leicht verständlichen deutschen Bezeichnungen auftreten. Während die ersten beiden Formen kaum ersetzt werden können ohne Verwirrung zu schaffen, erschweren Anglizismen der letzten Form das Textverständnis unnötig. Solche Anglizismen verdrängen oft gute und aussagekräftige deutsche Wörter. Auch international tätige Unternehmen tun gut daran, Bewerber in der Landessprache anzusprechen.
                    </div>

                    <h3 class="uk-accordion-title" style="background: #8ffce6; border: 1px solid #444;">Nominalstil<i class="accordion-arrow uk-icon-chevron-down"></i>
                    </h3>

                    <div class="uk-accordion-content">Als Nominalstil bezeichnet man Satzkonstruktionen mit übermäßig vielen Substantiven und Substantivierungen. Der Nominalstil wird hauptsächlich in der Behörden- und Wissenschaftssprache verwendet. Er wirkt schwerfällig und distanziert. Im Gegensatz dazu wirkt eine verbale Ausdrucksweise anschaulich und lebendig. Kein Wunder, denn auch beim Sprechen verwenden wir hauptsächlich den Verbalstil. Der Verbalstil wirkt aktiver und emotionaler.
                        <br/><br/>
                        Substantivierungen lassen sich am besten an ihren Endungen (Suffixen) -keit, -heit, -mut, -nis, -schaft, -ung, -tum, -ling, -sal, -tion, -ive, -anz, -tät erkennen. Klicken Sie auf den Button „Nominalstil“. Die markierten Substantivierungen sollten Sie anschließend in den Verbalstil ändern.
                    </div>

                    <h3 class="uk-accordion-title" style="background: #f8deca; border: 1px solid #444;">Aktiv-Passiv<i class="accordion-arrow uk-icon-chevron-down"></i>
                    </h3>

                    <div class="uk-accordion-content">Das Passiv bezeichnet man auch als die Leideform eines Verbs. Es leidet auch der Leser. Wenn Sie ein treffendes Verb gefunden haben, sollten Sie es nicht in eine Passivkonstruktion pressen. Passivsätze machen jeden Text hölzern und langweilig. Beispiel gefällig?<br/>
                        Passiv: „Die Ampel wurde von dem Autofahrer übersehen.“<br/>
                        Aktiv: „Der Autofahrer übersah die Ampel.“<br/>
                        Passiv: „Das Problem kann von uns gelöst werden“.<br/>
                        Aktiv: „Wir können das Problem lösen" oder "Wir lösen das Problem“.<br/>
                        Die aktive Form eines Verbs klingt nicht nur besser, sie ist auch kürzer.
                    </div>

                    <h3 class="uk-accordion-title" style="background: #cfc0ff; border: 1px solid #444;">Wiederholungen<i class="accordion-arrow uk-icon-chevron-down"></i>
                    </h3>

                    <div class="uk-accordion-content">Wiederholungen können Stilmittel sein. Beispiele kennen Sie aus Reimen, aus Refrains und natürlich aus der Werbung. Die VW-Werbung "Er läuft und läuft und läuft ..." brannte die Langlebigkeit des Käfers über Jahrzehnte in die Hirne der Autofahrer. In Stellenanzeigen langweilen Wiederholungen praktisch immer. Abwechslung ist gefragt. Das Zauberwort heißt Synonyme. Ausdrücke, die den gleichen oder einen sehr ähnlichen Bedeutungsumfang haben, helfen uns aus der Patsche. Gut gewählte Synonyme machen Texte lebendiger und die Aussagen präziser. Statt zu arbeiten kann jemand aufgehen, sich befassen, beschäftigen, hantieren, etwas herstellen, montieren, nachdenken, etwas schaffen, tüfteln, verändern, wirken oder handeln.<br/>
                        <br/>
                        Der Text-Optimierer markiert für Sie Wiederholungen. In Synonym-Wörterbuchern oder Datenbanken finden Sie schnell andere Begriffe. Gerne empfehlen wir
                        <a href="http://www.wortschatz.uni-leipzig.de" target="_blank">www.wortschatz.uni-leipzig.de</a>,
                        <a href="http://www.woerterbuch.info" target="_blank">www.woerterbuch.info</a>,
                        <a href="http://www.duden.de/hilfe/synonyme" target="_blank">www.duden.de/hilfe/synonyme</a> und
                        <a href="http://www.openthesaurus.de" target="_blank">www.openthesaurus.de</a>
                    </div>

                    <h3 class="uk-accordion-title" style="background: #fffacc; border: 1px solid #444;">Wort- und Satzlänge<i class="accordion-arrow uk-icon-chevron-down"></i>
                    </h3>

                    <div class="uk-accordion-content">Wortwahl und Schreibstil sind wichtig. Daneben entscheiden Wort- und Satzlänge, ob Leser den Inhalt sofort verstehen. "Schreibe kurz!", rät uns Joseph Pulitzer. Die Presseagentur dpa. geht als Obergrenze für "optimale" Verständlichkeit von 9 Wörtern pro Satz aus. Ein Satz in der BILD-Zeitung besteht durchschnittlich aus nur 12 Wörtern. Der Text-Optimierer markiert alle Sätze mit mehr als 15 Wörtern. Mehrere Sprachwissenschaftler halten dies für die Obergrenze leicht verständlicher Texte. Verständlich schreiben heißt immer auch Wörter kürzen. Je kürzer ein Wort ist, desto intensiver und klarer ist es meist. "Liebe", "Trauer", "Hass", "Stolz", "Angst" - viele starke Wörter haben nur eine Silbe. Und sind darum viel kraftvoller und leichter verständlich als Umschreibungen wie "emotionale Befindlichkeit". Der Text-Optimierer markiert Wörter mit mehr als 14 Buchstaben.
                    </div>
                </div>


            </div>
        </div>
    </div>
</div>
<div style="display: none;" class="tempText"></div>
<div style="display: none;" class="tempText2"></div>
<div class="uk-modal" id="pdfFooter">
    <div class="uk-modal-dialog">
        <a class="uk-modal-close uk-close"></a>

        <form class="uk-form pdfForm">
            <fieldset data-uk-margin>
                <legend style="padding: 0;  margin-bottom: 5px;">Bericht Einstellung</legend>

                <div class="uk-form-controls uk-form-controls-text" style="display: inline-block;">
                    <label for="form-h-r">Deckseite</label><br>
                    <label><input type="radio" name="deckpage" value="1" checked> Ja</label>
                    <label><input type="radio" name="deckpage" value="0"> Nein</label>
                </div>
                <div class="uk-form-controls uk-form-controls-text" style="display: inline-block; margin-left: 25px;">
                    <label for="form-h-r">Schlussseite</label><br>
                    <label><input type="radio" name="lastpage" value="1" checked> Ja</label>
                    <label><input type="radio" name="lastpage" value="0"> Nein</label>
                </div>

                <h4 style="margin: 0;">Titel</h4>
                <input type="text" name="title" class="uk-width-1-1"/>
                <br>
                <h4 style="margin: 0;">Firmenname</h4>
                <input type="text" name="company" class="uk-width-1-1"/>
                <br>
                <h4 style="margin: 0;">Ansprechpartner</h4>
                <input type="text" name="contact" class="uk-width-1-1"/>
                <br>
                <h4 style="margin: 0;">Fußzeile</h4>
                <select name="footer" class="uk-width-1-1">
                    <option value="© 2014 - <?php echo date('Y'); ?> www.stellenanzeigen-texten.de powered bei aicovo gmbh">© 2014 - <?php echo date('Y'); ?> www.stellenanzeigen-texten.de powered bei aicovo gmbh</option>
                    <option value="© 2014 - <?php echo date('Y'); ?> aicovo gmbh - www.aicovo.com">© 2014 - <?php echo date('Y'); ?> aicovo gmbh - www.aicovo.com</option>
                    <option value="© 2014 - <?php echo date('Y'); ?> Quergeist - Axel Haitzer">© 2014 - <?php echo date('Y'); ?> Quergeist - Axel Haitzer</option>
                    <option value="">- kein Text -</option>
                </select>
                <input type="hidden" name="id" value="0" />
                <br>
                <div style="margin-top: 20px !important; text-align: right;">
                    <a href="#" class="reportSave uk-button"><i class="uk-icon-save"></i> Bericht speichern</a>
                    <button class="uk-button uk-button-success"><i class="uk-icon-file-pdf-o"></i> Bericht erstellen</button>
                </div>
            </fieldset>
        </form>
    </div>
</div>
<script type="text/javascript">
$(document).ready(function () {
    $('.pdfForm').submit(function (e) {
        e.preventDefault();

        $('.tempText2').empty();
        var arrForm = $(this).serializeArray();
        var objContent = $('.tempText2').append(tinyMCE.activeEditor.getContent({format: 'raw'}));

        for (i = 0; i < 10; i++) {
            $(objContent).find('span').each(function () {
                try {
                    this.outerHTML = this.innerHTML;
                } catch (err) {
                    console.log('ErrorMessage: ' + err.message + ',   Element: ' + this + ',   Klasse: ' + $(this).attr('class') + ',   ID: ' + $(this).attr('id') + '\n\n' + err.stack);
                }
            });
        }
        var strHTML = objContent.html();

        objContent.empty();
        $.fileDownload('/check/public/includes/ajax/editor.php', {
            httpMethod: 'POST',
            data: {
                action:   'printPDF',
                text:     strHTML,
                deckPage: arrForm[0]['value'],
                lastPage: arrForm[1]['value'],
                title:    arrForm[2]['value'],
                company:  arrForm[3]['value'],
                contact:  arrForm[4]['value'],
                footer:   arrForm[5]['value']
            }
        }).done(function (e){
            //UIkit.modal("#pdfFooter").hide();
        }).fail(function (e) {
            alert('Es ist ein Fehler beim generieren der PDF Datei aufgetreten, bitte versuchen Sie es erneut.\nError: ' + e);
        });
        strHTML = "";
    });

    // Init Editor
    strEditorId = 'textarea_1';
    boolOldMode = 0;
    createEditor(strEditorId, function (ed) {
        ed.addButton("printPDF", {
            id:      "printPDFAdmin",
            classes: "widget btn buttonDisable",
            tooltip: "Alles Drucken",
            icon:    "fileTextO",
            onclick: function () {
                var modal = UIkit.modal("#pdfFooter");

                if (modal.isActive())
                    modal.hide();
                else
                    modal.show();
            }
        });

        ed.addButton("printSinglePDF", {
            id:           "printPDFNormal",
            classes:      "widget btn buttonDisable",
            tooltip:      "Drucken",
            icon:         "print",
            onclick:      function () {
                $.fileDownload('/check/public/includes/ajax/editor.php',
                    {
                        httpMethod: 'POST',
                        data:       {
                            action: 'printSinglePDF',
                            text:   ed.getContent({format: 'raw'})
                        }
                    })
                    .fail(function (e) {
                        alert('Es ist ein Fehler beim generieren der PDF Datei aufgetreten, bitte versuchen Sie es erneut.\nError: ' + e);
                    });
            },
            onPostRender: function () {
                console.log(this);
            }
        });
    });

    var activeButtonset = '';
    $('.editorButton').click(function () {
        var $objButton = $(this);
        var strAction = $(this).data().action
        var objActiveEditor = tinyMCE.activeEditor;
        thisButtonset = $(this).parent().attr('id');

        arrColorsToButtons = new Object();
        arrColorsToButtons['floskeln']              = 'highlight_blue';
        arrColorsToButtons['textverstaendnis']      = 'highlight_orange';
        arrColorsToButtons['anglizismen']           = 'highlight_red';
        arrColorsToButtons['aktiv_passiv']          = 'highlight_lightgreen';
        arrColorsToButtons['nominalstil']           = 'highlight_lightblue';
        arrColorsToButtons['wiederholungen']        = 'highlight_plumbpink';
        arrColorsToButtons['wortlaenge']            = 'highlight_pink';
        arrColorsToButtons['lange_saetze']          = 'highlight_yellow';

        // falls der Button aktiv geschaltet ist entfernen wir bei erneutem Klick das Highlighting
        if ($(this).hasClass('active'))
        {
            $objButton.toggleClass("active");
            clearMarksByClassName($(this).attr('id'));
        }
        // andernfalls prüfen wir den Text und fügen das Highlighting hinzu
        else {
            // falls die aktuelle Spalte nicht der aktiven Spalte entspricht
            if (activeButtonset != thisButtonset) {
                // Markierungen entfernen
                markierungenAufheben(strEditorId, 'Ma_parent_' + strEditorId);

                // active-Markierung entfernen
                if (activeButtonset != '' && thisButtonset != activeButtonset) {
                    $('#' + activeButtonset + ' a').removeClass('active');
                }
                activeButtonset = thisButtonset;
            }

            $.ajax({
                url:        "/check/public/includes/ajax/editor.php",
                method:     'post',
                async:      true,
                data:       {
                    action: strAction,
                    old:    boolOldMode,
                    text:   objActiveEditor.getContent({format: 'raw'})
                },
                beforeSend: function (jqXHR) {
                    jqXHR.overrideMimeType('text/html;charset=utf-8');
                    $objButton.toggleClass("active");
                },
                success:    function (data) {

                    /*
                     Temp speicherung des Textes

                     Das DIV wird als Temp Speicher verwendet, da jQuery mit großen Texten nicht arbeiten kann
                     und diese einfach abschneidet.
                     */
                    var objContent = $('.tempText').append(data);

                    // Suche nach allen Spans im Text
                    var objSpans = objContent.find('span');

                    function cloneClasses(objParent, objChild) {
                        // Git eine Array mit allen Klassen eines Objekts
                        var arrParentClasses = objParent[0].classList;
                        if (arrParentClasses.length > 0) {
                            for (i in arrParentClasses) {
                                if (typeof arrParentClasses[i] == "string") {
                                    // Falls Classe nicht im Kind Object vorhanden ist wird sie hinzugefügt
                                    if (!objChild.hasClass(arrParentClasses[i]))
                                        objChild.addClass(arrParentClasses[i]);
                                }
                            }
                        }
                    }

                    // Geht alle Spans in einer Schleife durch
                    objSpans.each(function () {
                        var objSpan = $(this);
                        var objParent = objSpan.parent();

                        // Überprüft ob der parent ein SPAN ist
                        if (objParent.prop("tagName") == "SPAN" && objParent[0].classList.length > 0) {
                            cloneClasses(objParent, objSpan);
                        }

                        // Geht alle Kind Objekte des Span durch
                        objSpan.children().each(function () {
                            // Überprüft ob das Kind ein SPAN ist
                            if ($(this).prop("tagName") == "SPAN") {
                                cloneClasses(objSpan, $(this));
                            }
                        });
                    });

                    // setzt den Editor Inhalt
                    objActiveEditor.setContent(objContent.html());

                    // leert den Temp Speicher
                    objContent.empty();
                }
            });
        }
    });

    function clearMarksByClassName(className)
    {
        var boolSpanHasChildren = false;
        $('iframe').contents().find('span').each(function () {
            var spanClassLength = this.classList.length;
            var objSpan         = $(this);

            if(objSpan.find('span.'+className).length > 0)
            {
                boolSpanHasChildren = true;
                return;
            }
            console.log(this);
            if(spanClassLength == 0 || (spanClassLength == 1 && objSpan.hasClass(className)))
                objSpan.replaceWith(objSpan.html());
            else if(objSpan.hasClass(className))
                objSpan.removeClass(className);
        });

        if(boolSpanHasChildren)
            clearMarksByClassName(className);
    }

    $('#markierungenAufheben').click(function (e) {
        e.preventDefault();
        markierungenAufheben(strEditorId, 'Ma_parent_' + strEditorId);
        $('[id^="buttonset_"] a').removeClass('active');
    });

    <?php if(isset($arrStandardText) && count($arrStandardText) > 0): ?>
    arrStandardTextCache = new Object();
    $('.standardtextButton').click(function (e) {
        var objActiveEditor = tinyMCE.activeEditor;
        var intId = $(this).data().id;
        e.preventDefault();
        if (isNaN(intId))
            return false;

        if (!arrStandardTextCache[intId]) {
            $.ajax({
                method: 'post',
                url:    '<?php echo $this->url('homepage/default', array('controller' => 'Admin', 'action' => 'ajaxStandardText'));?>',
                data:   { id: intId}
            }).done(function (data) {
                arrStandardTextCache[intId] = data;
                objActiveEditor.setContent(data);

                var intTextLength = objActiveEditor.getContent().length;
                if (intTextLength <= 0)
                    $('#printPDFNormal, #printPDFAdmin').addClass('mce-buttonDisable');
                else
                    $('#printPDFNormal, #printPDFAdmin').removeClass('mce-buttonDisable');
            });
        }
        else {
            objActiveEditor.setContent(arrStandardTextCache[intId]);
        }

        markierungenAufheben(strEditorId, 'Ma_parent_' + strEditorId);
        $('[id^="buttonset_"] a').removeClass('active');

    });
    <?php endif; ?>

    $('.reportSave').click(function(e){
        e.preventDefault();
        var arrFormTemp     = $('.pdfForm').serializeArray();
        var arrForm         = {};

        for(i in arrFormTemp)
        {
            var curr = arrFormTemp[i];
            arrForm[curr.name] = curr.value;
        }

        if(arrForm.id > 0)
            if(!window.confirm("Sind Sie sich sicher, das Sie den Bericht überschreiben wollen ?"))
                return;

        arrForm['content'] = tinyMCE.activeEditor.getContent({format: 'raw'});

        $.ajax({
            method:     'POST',
            url:        'http://www.stellenanzeigen-texten.de/check/public/homepage/Admin/ajaxSaveReport',
            data:       arrForm,
            dataType:   'json'
        }).done(function(data){
            if(data.status == 'ok')
            {
                $('.pdfForm input[name="id"]').val(data.id);
                if (arrReportCache[data.id])
                    delete arrReportCache[data.id];

                if($('.reportList li[data-id="'+data.id+'"]').length == 0)
                {
                    var strName = arrForm.title + ' / ' + arrForm.company;
                    var strHTML = '<li data-id="'+data.id+'">' +
                                      strName+' ' +
                                      '<div style="float: right">' +
                                          '<a class="reportLoad uk-icon-hover uk-icon-share" title="Lade '+strName+'" data-id="'+data.id+'" href="#"></a> ' +
                                          '<a class="reportTrash uk-icon-hover uk-icon-trash-o" title="Lösche '+strName+'" data-id="'+data.id+'" href="#"></a>' +
                                      '</div>' +
                                  '</li>'
                    $('.reportList').prepend(strHTML);

                    if($('.savedReports').css('display') == 'none')
                        $('.savedReports').css('display', 'block');

                    bindReportClick();
                }

                if(arrForm.id > 0)
                    alert('Bericht überschrieben');
                else
                    alert('Bericht gespeichert');
            }
            else
                alert('Ein Fehler ist beim speichern des Berichts aufgetreten, bitte kontaktieren Sie einen Techniker !');
        });
    });
    <?php if(isset($arrReports)): ?>
    arrReportCache = new Object();
    function bindReportClick()
    {
        $('.reportLoad').unbind();
        $('.reportLoad').click(function(e){
            e.preventDefault();
            var intId               = $(this).data().id;

            if (!arrReportCache[intId])
            {
                $.ajax({
                    method:     'post',
                    url:        '<?php echo $this->url('homepage/default', array('controller' => 'Admin', 'action' => 'ajaxGetReport'));?>',
                    data:       { id: intId},
                    dataType:   'json'
                }).done(function (data) {
                    arrReportCache[intId]   = data;
                    reportFillData(data);
                });
            }
            else
                reportFillData(arrReportCache[intId]);
        });

        $('.reportTrash').unbind();
        $('.reportTrash').click(function(e){
            e.preventDefault();

            if(!window.confirm("Sind Sie sich sicher, dass Sie diesen Bericht löschen möcten ?"))
                return;

            var intId               = $(this).data().id;
            var self                = this;
            if (arrReportCache[intId])
                delete arrReportCache[intId];

            $.ajax({
                method:     'post',
                url:        '<?php echo $this->url('homepage/default', array('controller' => 'Admin', 'action' => 'ajaxDeleteReport'));?>',
                data:       { id: intId},
                dataType:   'json'
            }).done(function (data) {
                if(data.status == 'ok')
                {
                    var objId = $('.pdfForm input[name="id"]');
                    if(objId.val() == intId)
                        objId.val(0);

                    $(self).parent().parent().remove();

                    if($('.reportList li').length <= 0)
                        $('.savedReports').hide();
                }
                else
                    alert('Ein Fehler ist beim löschen des gespeicherten Berichts aufgetreten, bitte kontaktieren Sie einen Techniker !');
            });
        });
    }
    bindReportClick();

    function reportFillData(arrData)
    {
        var objActiveEditor     = tinyMCE.activeEditor;

        // fill editor
        objActiveEditor.setContent(arrData.content);
        var intTextLength = objActiveEditor.getContent().length;
        if (intTextLength <= 0)
            $('#printPDFNormal, #printPDFAdmin').addClass('mce-buttonDisable');
        else
            $('#printPDFNormal, #printPDFAdmin').removeClass('mce-buttonDisable');

        // fill report form
        $('.pdfForm input[name="deckpage"]').prop('checked', false);
        $('.pdfForm input[name="deckpage"][value="'+arrData.deckpage+'"]').prop('checked', true);

        $('.pdfForm input[name="lastpage"]').prop('checked', false);
        $('.pdfForm input[name="lastpage"][value="'+arrData.lastpage+'"]').prop('checked', true);

        $('.pdfForm input[name="title"]').val(arrData.title);
        $('.pdfForm input[name="company"]').val(arrData.company);
        $('.pdfForm input[name="contact"]').val(arrData.contact);
        $('.pdfForm input[name="id"]').val(arrData.id);

        $('.pdfForm select[name="footer"] option').prop('selected', false);
        $('.pdfForm select[name="footer"] option[value="'+arrData.footer+'"]').prop('selected', true);
    }
    <?php endif; ?>

    $('.debugButton').show();
    objDebugInterval = null;
    $('.debugButton').click(function (e) {
        if (objDebugInterval != null) {
            $(this).css('background-color', '');
            clearInterval(objDebugInterval);
            objDebugInterval = null;
            return;
        }
        else {
            $(this).css('background-color', '#CAF8DA');
        }

        objDebugInterval = setInterval(function () {
            var arrButton = $('.pruef-buttons a');
            var intButtonLen = arrButton.length - 1;
            var intRandId = Math.floor((Math.random() * intButtonLen) + 0);
            var objButton = $(arrButton[intRandId]);
            objButton.trigger("click");
        }, 150);
    });

    $('.oldModeButton').click(function (e) {
        if (boolOldMode == 0) {
            $(this).css('background-color', '#CAF8DA');
            boolOldMode = 1;
        }
        else {
            $(this).css('background-color', '');
            boolOldMode = 0;
        }
    });

    $('[data-uk-accordion]').on('toggle.uk.accordion', function (event, active, toggle, content) {
        $('[data-uk-accordion] .uk-accordion-title .accordion-arrow').each(function () {
            $(this).removeClass("uk-icon-chevron-up").addClass('uk-icon-chevron-down ');
        });
        if (active)
            $(toggle).find('.accordion-arrow').removeClass("uk-icon-chevron-down").addClass("uk-icon-chevron-up");
    });
});
</script>
</div>