<div class="middle">
	<div class="uk-container uk-container-center">
		<div class="uk-grid uk-grid-divider">			
			<div class="uk-width-3-4">
				<h1>Das hat geklappt !</h1>
				<div class='page_content'>
                    <p>Herzlichen Dank für Ihre kostenfreie Registrierung bei stellenanzeigen-texten.de.</p><br><br>
                    <p>In wenigen Minuten erhalten Sie eine E-Mail mit Ihren persönlichen Zugangdaten.<br>
                    Nach der Freischaltung können sich dann bei stellenanzeigen-texten.de einloggen und <br>
                    die Funktionen des Portals nutzen.</p><br>
                    <p>Wenn Sie die E-Mail nicht erhalten, schauen Sie bitte in Ihren Spam-Ordner.<br>
                    In den meisten Fällen findet sich dort die vermisste Nachricht.</p>
                    <div>
                    <?php
                    if(!$this->isActiv){
                        $form = $this->form;
                        $form->setAttribute('action', $this->url('auth/default', array('controller' => 'registration', 'action' => 'confirm-email')).'/'.$this->token);
                        $form->prepare();
                        
                        
                        echo $this->form()->openTag($form);
                        ?>
                        <div class='registration_formular'>
                            <div class='div_row'>
                                <div class='reg_label'>Firmenname *</div>
                                <div class='reg_textfield'>
                                    <input type="text" class="form-control" value="<?=$this->objUser->user_firmenname?>" disabled>
                                </div>
                            </div>
                            <div class='div_row'>
                                <div class='reg_label'>Anrede *</div>
                                <div class='reg_textfield'>
                                    <select class="form-control" disabled>
                                        <option <?=($this->objUser->user_anrede == '' ? 'selected' : '')?>>Bitte wählen</option>
                                        <option <?=($this->objUser->user_anrede == 'Herr' ? 'selected' : '')?>>Frau</option>
                                        <option <?=($this->objUser->user_anrede == 'Frau' ? 'selected' : '')?>>Herr</option>
                                    </select>
                                </div>
                            </div>
                            <div class='div_row'>
                                <div class='reg_label'>Titel</div>
                                <div class='reg_textfield'>
                                    <select class="form-control" disabled>
                                        <option <?=($this->objUser->user_titel == '' ? 'selected' : '')?>>-</option>
                                        <option <?=($this->objUser->user_titel == 'Doktor' ? 'selected' : '')?>>Doktor</option>
                                        <option <?=($this->objUser->user_titel == 'Professor' ? 'selected' : '')?>>Professor</option>
                                    </select>
                                </div>
                            </div>
                            <div class='div_row'>
                                <div class='reg_label'>Vorname *</div>
                                <div class='reg_textfield'>
                                    <input type="text" class="form-control" value="<?=$this->objUser->user_vorname?>" disabled>
                                </div>
                            </div>
                            <div class='div_row'>
                                <div class='reg_label'>Nachname *</div>
                                <div class='reg_textfield'>
                                    <input type="text" class="form-control" value="<?=$this->objUser->user_nachname?>" disabled>
                                </div>
                            </div>
                            <div class='div_row'>
                                <div class='reg_label'>E-Mail *</div>
                                <div class='reg_textfield'>
                                    <input type="text" class="form-control" value="<?=$this->objUser->user_email?>" disabled>
                                </div>
                            </div>
                            <div class='div_row'>
                                <div class='reg_label'>Passwort *</div>
                                <div class='reg_textfield'>
                                    <input type="password" class="form-control" value="..............." disabled>
                                </div>
                            </div>

                            <div class='div_row'>
                                <div class='reg_label'>Land</div>
                                <div class='reg_textfield'><?php echo $this->formRow($form->get('user_land')); ?></div>
                            </div>
                            <div class='div_row'>
                                <div class='reg_label'>Straße / Nr.</div>
                                <div class='reg_textfield'><?php echo $this->formRow($form->get('user_strasse')); 
                                                                 echo $this->formRow($form->get('user_hausnummer'));?>
                                </div>
                            </div>
                            <div class='div_row'>
                                <div class='reg_label'>PLZ / Ort</div>
                                <div class='reg_textfield'><?php echo $this->formRow($form->get('user_plz')); echo $this->formRow($form->get('user_ort')); ?></div>
                            </div>
                            <div class='div_row'>
                                <div class='reg_label'>Ländervorwahl</div>
                                <div class='reg_textfield'><?php echo $this->formRow($form->get('user_laendervorwahl')); ?></div>
                            </div>
                            <div class='div_row'>
                                <div class='reg_label'>Vorwahl / Telefonnummer</div>
                                <div class='reg_textfield'><?php echo $this->formRow($form->get('user_vorwahl')); echo $this->formRow($form->get('user_telefon')); ?></div>
                            </div>
                            <div class='div_row'>
                                <div class='reg_label'>AGB *</div>
                                <div class='reg_textfield checkbox_text'><?php echo $this->formRow($form->get('user_agb')); ?> <a href='#'>Ich habe die allgemeinen Geschäftsbedingungen gelesen und akzeptiert</a></div>
                            </div>

                            <div class='div_row'>
                                <div class='reg_label'>Datenschutz *</div>
                                <div class='reg_textfield checkbox_text'><?php echo $this->formRow($form->get('user_datenschutz')); ?> <a href='#'>Ich habe die Datenschutzbestimmungen gelesen und akzeptiert</a></div>
                            </div>
                            <div>
                                <div class='submit'><?php echo $this->formSubmit($form->get('user_submit')); ?></div>
                                <?php
                                echo $this->form()->closeTag();
                                ?>
                            </div>
                        </div>
                    <?php } else { ?>
                        <h3>Sie haben bereits Ihren Account aktiviert !</h3>
                    <?php } ?>
                    </div>
                </div>
			</div>
		</div>
	</div>	
</div>