
<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle('Stellenanzeigen texten')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/index.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/CreateNewButtons.js')
            ->prependFile($this->basePath() . '/js/added_functions.js')
            ->prependFile($this->basePath() . '/tinymce_4.0.11/tinymce/js/tinymce/tinymce.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class='main-content'>
<div>
    <div class="ueberschrift_nav">
        <h1>Registrierung</h1>
        
    </div>
</div>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('auth/default', array('controller' => 'registration', 'action' => 'indexiframe')));
$form->prepare();


echo $this->form()->openTag($form);
?>
<div class='registration_formular'>
    <div class='div_row'>
        <div class='reg_label'>Firmenname</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_firmenname')); ?></div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>Anrede *</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_anrede')); ?></div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>Titel</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_titel')); ?></div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>Vorname *</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_vorname')); ?></div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>Nachname *</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_nachname')); ?></div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>Land</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_land')); ?></div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>Straße / Nr.</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_strasse')); 
                                         echo $this->formRow($form->get('user_hausnummer'));?>
        </div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>PLZ / Ort</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_plz')); echo $this->formRow($form->get('user_ort')); ?></div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>E-Mail *</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_email')); ?></div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>Passwort *</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_passwort')); ?></div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>Ländervorwahl</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_laendervorwahl')); ?></div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>Vorwahl / Telefonnummer</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_vorwahl')); echo $this->formRow($form->get('user_telefon')); ?></div>
    </div>

    <div class='div_row'>
        <div class='reg_label'>AGB *</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_agb')); ?></div>
        <a href='#'>Ich habe die allgemeinen Geschäftsbedingungen gelesen und akzeptiert</a>
    </div>

    <div class='div_row'>
        <div class='reg_label'>Datenschutz *</div>
        <div class='reg_textfield'><?php echo $this->formRow($form->get('user_datenschutz')); ?></div>
        <a href='#'>Ich habe die Datenschutzbestimmungen gelesen und akzeptiert</a>
    </div>
    


    <div><div class='submit'><?php echo $this->formSubmit($form->get('user_submit')); ?></div>

        <?php
        echo $this->form()->closeTag();
        ?>
</div>
    </body>
</html>
