<div class="middle">
	<div class="uk-container uk-container-center">
		<div class="uk-grid uk-grid-divider">			
			<div class="uk-width-3-4">
				<h1>Registrierung</h1>
				
				<div class='page_content'>
                    <?php
                    $form = $this->form;
                    $form->setAttribute('action', $this->url('auth/default', array('controller' => 'registration', 'action' => 'index')));
                    $form->prepare();
                                        
                    echo $this->form()->openTag($form);
                    ?>
                    <div class='registration_formular'>
                        <div class='div_row'>
                            <div class='reg_label'>Firmenname</div>
                            <div class='reg_textfield'><?php echo $this->formRow($form->get('user_firmenname')); ?></div>
                        </div>
                    
                        <div class='div_row'>
                            <div class='reg_label'>Anrede *</div>
                            <div class='reg_textfield'><?php echo $this->formRow($form->get('user_anrede')); ?></div>
                        </div>
                    
                        <div class='div_row'>
                            <div class='reg_label'>Titel</div>
                            <div class='reg_textfield'><?php echo $this->formRow($form->get('user_titel')); ?></div>
                        </div>
                    
                        <div class='div_row'>
                            <div class='reg_label'>Vorname *</div>
                            <div class='reg_textfield'><?php echo $this->formRow($form->get('user_vorname')); ?></div>
                        </div>
                    
                        <div class='div_row'>
                            <div class='reg_label'>Nachname *</div>
                            <div class='reg_textfield'><?php echo $this->formRow($form->get('user_nachname')); ?></div>
                        </div>

                        <div class='div_row'>
                            <div class='reg_label'>E-Mail *</div>
                            <div class='reg_textfield'><?php echo $this->formRow($form->get('user_email')); ?></div>
                        </div>
                    
                        <div class='div_row'>
                            <div class='reg_label'>Passwort *</div>
                            <div class='reg_textfield'><?php echo $this->formRow($form->get('user_passwort')); ?></div>
                        </div>

                        <div>
                            <div class='submit'><?php echo $this->formSubmit($form->get('user_submit')); ?></div>
                            <?php
                            echo $this->form()->closeTag();
                            ?>
                        </div>
                    </div>
                </div>			
			</div>
		</div>
	</div>	
</div>