<?php echo $this->doctype(); ?>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php echo $this->headTitle('Stellenanzeigen texten')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
                        ->prependStylesheet($this->basePath() . '/css/index.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/CreateNewButtons.js')
            ->prependFile($this->basePath() . '/js/added_functions.js')
            ->prependFile($this->basePath() . '/tinymce_4.0.11/tinymce/js/tinymce/tinymce.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <div class='main-content'>
                <h1>Vielen Dank für Ihre Registrierung !</h1>
                <br>
                <p>In wenigen Minuten erhalten Sie eine E-Mail mit einem Aktivierungslink.<br>
                Bitte klicken Sie auf den Link in dieser Mail, um Ihre Registrierung zu<br> 
                aktivieren.</p>
                <p>Mit diesem Verfahren stellen wir sicher, dass tatsächlich Sie die Registrierung<br>
                veranlasst haben.</p><br>
                <p>Wenn Sie die E-Mail nicht erhalten, schauen Sie bitte in Ihren Spam-Ordner.<br>
                In den meisten Fällen findet sich dort die vermisste Nachricht.</p>
        </div>
    </body>
</html>
