<div class="middle">
	<div class="uk-container uk-container-center">
		<div class="uk-grid uk-grid-divider">			
			<div class="uk-width-3-4">
				<h1>Registrierung</h1>
				<div class='page_content'>
                    <p>In wenigen Minuten erhalten Sie eine E-Mail mit einem Aktivierungslink.<br>
                    Bitte klicken Sie auf den Link in dieser Mail, um Ihre Registrierung zu<br> 
                    aktivieren.</p>
                    <p>Mit diesem Verfahren stellen wir sicher, dass tatsächlich Sie die Registrierung<br>
                    veranlasst haben.</p><br>
                    <p>Wenn Sie die E-Mail nicht erhalten, schauen Sie bitte in Ihren Spam-Ordner.<br>
                    In den meisten Fällen findet sich dort die vermisste Nachricht.</p>
                </div>
			</div>
		</div>
	</div>	
</div>