<?php
echo $this->doctype();

?>

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php
            echo $this->headTitle('Stellenanzeigen texten')->setSeparator(' - ')->setAutoEscape(false);
            echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');
        ?>
        
        <!-- CSS -->
        <?php echo $this->headLink()
						->prependStylesheet($this->basePath() . '/css/custom.css')
                        ->prependStylesheet($this->basePath() . '/css/uikit.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/CreateNewButtons.js')
            ->prependFile($this->basePath() . '/js/uikit.min.js')
            ->prependFile($this->basePath() . '/js/added_functions.js')
            ->prependFile($this->basePath() . '/tinymce_4.0.11/tinymce/js/tinymce/tinymce.min.js')
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/excanvas.compiled.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/jquery.fileDownload.js')
            ->prependFile($this->basePath() . '/js/function.js')
            ->prependFile($this->basePath() . '/js/jquery.autosize.min.js')
            ->prependFile($this->basePath() . '/js/jquery-ui.min.js')
            ->prependFile($this->basePath() . '/js/jquery-1.11.1.min.js');
        ?>
    </head>
            <?php echo $this->content; ?>
        </div>    
        <div class="footer">
        	<div class="uk-container uk-container-center">
        	   <hr class="uk-grid-divider">
        	   <center>© Copyright 2014 - <?=date('Y');?>, alle Rechte vorbehalten aicovo gmbh</center>
               <br/>
               <br/>
               </div>
               </div>
        	</div>
        </div>  
    </body>
</html>

